# Generated by Django 6.0.2 on 2026-02-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_exame_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='dias_atendimento',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
